version: '3.8'
services:
  vaayu-db:
    image: postgres:15-alpine
    container_name: vaayu_postgres
    restart: always
    environment:
      POSTGRES_USER: vaayu_admin
      POSTGRES_PASSWORD: super_secure_password_123
      POSTGRES_DB: vaayu_health
    ports:
      - "5432:5432"
    volumes:
      - vaayu_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  vaayu_data: